version: "3.3"

#Docker Networks
networks:
  sandbox:
    driver: bridge

# Volumes
volumes:
  espresso_mysql_data:
    driver: local

services:

  # Application service
  espresso:
    image: espresso:1.0
    container_name: espresso
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/espresso
      - "/code/espresso/node_modules"
    networks:
      - sandbox

  # Mysql service
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: webdevel
    volumes:
      - espresso_mysql_data:/var/lib/mysql/
    networks:
      - sandbox

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    logging:
      options:
        max-size: 1g
