version: "3.3"

#Docker Networks
networks:
  nodejs:
    driver: bridge

#Volumes
volumes:
  MYSQL:
    driver: local
  REDIS:
    driver: local
  MONGO:
    driver: local

services:

  # Mysql service   
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: espresso
      MYSQL_ROOT_PASSWORD: webdevel
    volumes:
      - MYSQL:/var/lib/mysql/
      - //DATA/espresso/docker/mysql/8.0/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - nodejs

  # Phpmyadmin service
  phpmyadmin:
    image: phpmyadmin:5.0
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - nodejs
    depends_on:
      - mysql

  # Redis service
  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - REDIS:/data
    networks:
      - nodejs 
 
  # Mongo service
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    container_name: mongo
    restart: always    
    volumes: 
      - MONGO:/data/db
    networks:
      - nodejs

  # Mongo client service
  mongoku:
    image: huggingface/mongoku
    container_name: mongoku
    ports:
      - "3100:3100"
    networks:
      - nodejs

  # Application service
  espresso:
    image: espresso:1.0
    container_name: espresso
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "80:3000"
    volumes:
      - //DATA/espresso:/var/www/espresso      
      - "/var/www/espresso/node_modules"
    networks:
      - nodejs
    depends_on:
      - mongo
     