### Api user
GET http://localhost:3000/api/v1/users

### Login - from
GET http://localhost:3000/admin/login

### Login
POST http://localhost:3000/admin/login
content-type: application/json

{
    "_csrf" : "7xgBtnHp-8t73rRSWmn7dFunpkLqa4W1XlNg",
    "username": "admin@gmail.com" ,
    "password" : "password"
}

### All users
GET http://localhost:3000/admin/users
